// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	solveQuiz: (html: string) => __TAURI_INVOKE<AnswerItem_Serialize[]>("solve_quiz", { html }),
	insertCourseMetaMap: (courseId: string, metadata: CourseMetadata) => __TAURI_INVOKE<void>("insert_course_meta_map", { courseId, metadata }),
	queryCourseMeta: (courseId: string) => __TAURI_INVOKE<{
	title: string,
	cover: string,
} | null>("query_course_meta", { courseId }),
	sendStatus: (status: CourseStatus) => __TAURI_INVOKE<null>("send_status", { status }),
	platform: () => __TAURI_INVOKE<string>("platform"),
	/**  从本地 Ollama 服务拉取可用模型列表更新至内存配置。 */
	fetchOllamaModels: () => __TAURI_INVOKE<null>("fetch_ollama_models"),
	/**  获取当前可用的全部大语言模型提供商列表。 */
	providers: () => __TAURI_INVOKE<LLMProvider[]>("providers"),
	/**  获取当前选中的大语言模型提供商。 */
	currentProvider: () => __TAURI_INVOKE<string>("current_provider"),
	/**  新增或更新一个自定义大语言模型提供商。 */
	upsertProvider: (provider: LLMProvider) => __TAURI_INVOKE<null>("upsert_provider", { provider }),
	/**  移除一个自定义大语言模型提供商。 */
	removeProvider: (name: string) => __TAURI_INVOKE<null>("remove_provider", { name }),
	/**  将当前大语言模型提供商切换为指定提供商。 */
	switchProvider: (name: string) => __TAURI_INVOKE<null>("switch_provider", { name }),
	/**  将当前大语言模型提供商的选用模型切换为指定模型。 */
	switchModel: (index: number) => __TAURI_INVOKE<void>("switch_model", { index }),
	/**  设置当前大语言模型提供商的 API 密钥。 */
	setKey: (key: string) => __TAURI_INVOKE<null>("set_key", { key }),
	/**  获取包含版本及作者信息的应用元数据。 */
	metadata: () => __TAURI_INVOKE<MetadataConfig>("metadata"),
	options: () => __TAURI_INVOKE<OptionsConfig>("options"),
	setOptions: (options: OptionsConfig) => __TAURI_INVOKE<void>("set_options", { options }),
	/**  将内存中的全局配置持久化保存至本地文件。 */
	saveConfig: () => __TAURI_INVOKE<null>("save_config"),
	paths: () => __TAURI_INVOKE<PathsConfig>("paths"),
	/**  显示调用方对应的确认遮罩，并在退出动画及隐藏完成后返回选择。 */
	confirm: (message: string) => __TAURI_INVOKE<boolean>("confirm", { message }),
	/**  遮罩监听器就绪后显示窗口并发送开屏事件。 */
	startMask: () => __TAURI_INVOKE<null>("start_mask"),
	/**  显示初始化时隐藏的主界面和超星 Webview；此命令不检查页面加载状态。 */
	showContent: () => __TAURI_INVOKE<null>("show_content"),
	/**  异步隐藏遮罩，避免遮罩 Webview 在自身 IPC 调用链中等待可见性更新。 */
	hideMask: () => __TAURI_INVOKE<null>("hide_mask"),
	setZoom: (scale: number | null) => __TAURI_INVOKE<null>("set_zoom", { scale }),
	canGoBack: () => __TAURI_INVOKE<boolean>("can_go_back"),
	canGoForward: () => __TAURI_INVOKE<boolean>("can_go_forward"),
	goHome: () => __TAURI_INVOKE<null>("go_home"),
	goBack: () => __TAURI_INVOKE<null>("go_back"),
	goForward: () => __TAURI_INVOKE<null>("go_forward"),
	currentUrl: () => __TAURI_INVOKE<string | null>("current_url"),
	reload: () => __TAURI_INVOKE<null>("reload"),
	/**  发起窗口关闭请求；保存配置与退场动画由窗口事件监听器处理。 */
	close: () => __TAURI_INVOKE<void>("close"),
	/**  应用窗口最小化处理指令。 */
	minimize: () => __TAURI_INVOKE<void>("minimize"),
};

/* Types */
export type AnswerItem = AnswerItem_Serialize | AnswerItem_Deserialize;

export type AnswerItem_Deserialize = {
	index: string,
} | {
	"题号": string,
} | {
	id: string,
} & {
	explanation: string,
} | {
	"解析": string,
} & {
	content: string,
} | {
	"答案": string,
} | {
	answer: string,
};

export type AnswerItem_Serialize = {
	index: string,
	explanation: string,
	content: string,
};

/**
 *  API 密钥。
 * 
 *  序列化时保持原始字符串格式，以兼容现有配置文件；格式化输出始终脱敏，
 *  防止在日志中直接打印密钥明文。
 */
export type ApiKey = string;

export type ChapterProgressPayload = {
	title: string,
	index: number,
	completed: number,
	total: number,
};

export type CourseMetadata = {
	title: string,
	cover: string,
};

export type CourseStatus = { kind: "waiting"; payload: null } | { kind: "start"; payload: null } | { kind: "chapter"; payload: ChapterProgressPayload } | { kind: "tab"; payload: TabProgressPayload } | { kind: "task"; payload: TaskProgressPayload } | { kind: "cancel"; payload: null } | { kind: "finish"; payload: null };

/**  支持的大模型 API 发包协议族 */
export type LLMProtocol = "OpenAIChatCompletions" | "OpenAIResponses" | "GoogleGemini";

/**  统一的大模型提供商结构体（内置与用户自定义提供商通用纯数据 DTO） */
export type LLMProvider = {
	name: string,
	isCustom: boolean,
	protocol: LLMProtocol,
	baseUrl: string,
	apiKey: ApiKey | null,
	models: string[],
	chosenModel: number | null,
};

export type MetadataConfig = {
	author?: string,
	title?: string,
	version?: string,
	homeUrl?: string,
	logLevel?: string,
};

export type OptionsConfig = {
	persistSession?: boolean,
	muteWebview?: boolean,
	speedLock?: boolean,
	speedValue?: number | null,
};

export type PathsConfig = {
	dirs?: { [key in string]: string },
	files?: { [key in string]: string },
};

export type TabProgressPayload = {
	total: number,
	index: number,
};

export type TaskProgressPayload = {
	index: number,
	category: string,
};

