[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"
rustflags = [
    "-C",
    "target-cpu=x86-64-v3",
    "-C",
    "link-arg=/THREADS:16",
    "-C",
    "llvm-args=-enable-dfa-jump-thread",
]

[alias]
sync-bindings = "run -p uxuescript --bin sync-bindings --features sync-bindings"
